SPLIT_KEYBOARD = yes
SERIAL_DRIVER = vendor

PS2_DRIVER = vendor
PS2_ENABLE = yes
PS2_MOUSE_ENABLE = yes

MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
BOOTMAGIC_ENABLE = yes
CONSOLE_ENABLE = yes
LTO_ENABLE = yes
